server {
    listen 80;
    server_name superset.dai.post.gov.tw;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name superset.dai.post.gov.tw;

    ssl_certificate     /etc/nginx/ssl/fullcert_202606.crt;
    ssl_certificate_key /etc/nginx/ssl/dai_202606.key;

    include conf.d/security.conf;

    # 把不允許使用者存取的目錄導向 404（跟 nginx_vm3 一致的共通強化）
    location ~* ^/(css|js|img)/$ {
        return 404;
    }

    location / {
        resolver 127.0.0.11 valid=30s;
        set $upstream_superset "superset";

        proxy_pass http://$upstream_superset:8088;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
    }
}
